netctl-auto-monitor -> conmon: generalize to arbitrary service

diff --git a/root/bin/conmon b/root/bin/conmon
--- a/root/bin/conmon
+++ b/root/bin/conmon
@@ -1,73 +1,63 @@
 #!/bin/sh
 #
 # NAME
-#        netctl-auto-monitor - Restart netctl-auto when connection fails
+#        conmon - Restart service when connection fails
 #
 # SYNOPSIS
-#        netctl-auto-monitor INTERFACE INTERVAL USER
+#        conmon SERVICE INTERVAL
 #
 # DESCRIPTION
-#        Whenever the curl fails connect to all of the websites listed below
-#        (in the script), the script will attempt to restart the corresponding
-#        'netctl-auto@INTERFACE.service' via systemd.
+#        Whenever 'host' fails resolve to all of the domains listed below in
+#        this script, 'SERVICE.service' is restarted.
 #
 #        The time between periodic checks is fixed at a minimum of INTERVAL
 #        seconds.  In reality, it will probably be longer than that due to
 #        latency.  There are also some additional delays between the
-#        reconnects to allow the network interface to act, and also to prevent
-#        frequent but futile reconnections when network is down.  These
-#        timings can be adjusted via the 'init_pause' and 'max_pause'
-#        parameters.
+#        reconnects to allow the service to act, and also to prevent frequent
+#        but futile reconnections when network is down.  These timings can be
+#        adjusted via the 'init_pause' and 'max_pause' parameters.
 #
 #        The script must be run as root as it operates on systemd.  To reduce
-#        the danger of this, curl is executed under a separate USER, which
-#        should have minimal privileges.  One may create such a user via:
-#
-#          useradd -r -s /bin/false USER
+#        the danger of this, 'host' is executed under 'nobody'.
 #
 # OPTIONS
-#        INTERFACE
-#               Network interface to monitor.
+#        SERVICE
+#               Service to restart when the connection is down.
 #
 #        INTERVAL
 #               Time between periodic checks in seconds.
 #
-#        USER
-#               An unprivileged user under which curl is run.
-#
 # EXAMPLE
 #        The script itself may be managed via a systemd unit such as:
 #
-#          # /etc/systemd/system/netctl-auto-monitor@.service
+#          # /etc/systemd/system/conmon@.service
 #
 #          [Unit]
-#          Description=Restart netctl-auto when connection fails
-#          Wants=netctl-auto@%i.service
+#          Description=Restart service when connection fails
 #
 #          [Service]
-#          ExecStart=/usr/local/bin/netctl-auto-monitor %I 60 netctlautomonitor
+#          ExecStart=/usr/local/bin/conmon %I 60
 #          Restart=always
 #          RestartSec=600
 #
 #          [Install]
 #          WantedBy=multi-user.target
 #
-set -e
+set -eu
 
-if [ $# -ne 3 ]
+if [ $# -ne 2 ]
 then
     prog=`basename "$0"`
-    printf >&2 "usage: %s INTERFACE INTERVAL USER\n" "$prog"
+    printf >&2 "usage: %s SERVICE INTERVAL\n" "$prog"
     exit 2
 fi
 
-interface=$1
+service=$1
 interval=$2
-user=$3
 
-service=netctl-auto@$interface.service
+user=nobody
 timeout=30
-init_pause=10
+init_pause=30
 max_pause=600
 pause=$init_pause
 
@@ -75,17 +65,15 @@ pause=$init_pause
 # return 37 on immediate failure and 0 on subsequent failures
 test_connectivity() {
     cd "${TMP:-/tmp}"
-    if sudo -n -u "$user" interface="$interface" interval="$interval" \
-                          timeout="$timeout" sh <<"EOF"
+    if sudo -n -u "$user" interval="$interval" timeout="$timeout" sh <<"EOF"
 
-    check_url() {
-        curl -ISs --interface "$interface" -m "$timeout" "$1" >/dev/null
+    check_domain() {
+        host -W "$timeout" "$1" >/dev/null
     }
 
     check() {
-        check_url https://www.google.com    ||
-        check_url https://www.microsoft.com ||
-        check_url https://www.apple.com
+        check_domain cloudflare.com ||
+        check_domain amazon.com
     }
 
     exitcode=37
@@ -106,7 +94,7 @@ EOF
     fi
 }
 
-# allow some time for netctl-auto to initialize
+# allow some time for service to initialize
 # since it may have been started in parallel
 sleep "$pause"
 while :
