home/sbin/cryptloop: update

diff --git a/home/sbin/cryptloop b/home/sbin/cryptloop
--- a/home/sbin/cryptloop
+++ b/home/sbin/cryptloop
@@ -19,8 +19,14 @@
 
 set -e
 
-showhelp() {
-    printf >&2 '%s\n' "$0 [open|close] IMAGE MOUNT [DEVICE]"
+unset prog
+get_prog() {
+    [ "${prog+x}" ] || prog=`basename "$0"`
+}
+
+show_help() {
+    get_prog
+    printf >&2 '%s [open|close] IMAGE MOUNT [DEVICE]\n' "$prog"
     exit 1;
 }
 
@@ -32,11 +38,11 @@ esac
 
 # name of the image file
 img=$2
-[ "$img" ] || showhelp
+[ "$img" ] || show_help
 
 # name of the mount
 mount=$3
-[ "$mount" ] || showhelp
+[ "$mount" ] || show_help
 
 # loop device
 dev=${4-/dev/loop0}
@@ -45,7 +51,8 @@ then :
 elif printf '%s' "$dev" | grep >/dev/null 2>/dev/null "[0-9][0-9]*"
 then dev=/dev/loop$dev
 else
-    printf >&2 '%s\n' "'$dev' doesn't appear to be a valid loop device"
+    get_prog
+    printf >&2 "%s: '%s' doesn't seem to be a valid loop device\n" "$prog" "$dev"
     exit 1
 fi
 
@@ -60,7 +67,13 @@ name=`printf '%s' "$dir/$base" | md5sum | head -c 16`
 case $action in
 
     open)                               # mount
-        modprobe loop
+        modprobe loop || {
+            get_prog
+            printf >&2 "%s: can't load kernel module\n" "$prog"
+            printf >&2 "%s: are you root? " "$prog"
+            printf >&2 "have you updated the kernel recently?\n"
+            exit 1
+        }
         losetup "$dev" "$img"
         if cryptsetup open "$dev" "$name"
         then :
@@ -85,5 +98,5 @@ case $action in
         losetup -d "$dev"
         ;;
 
-    *)  showhelp;;
+    *)  show_help;;
 esac
